### ISSUE TITLE
Failed report generation

### ISSUE THREAD

**Issue by alexpdp7** [cloudflare/flan#11]
```
# Nmap done at Fri Nov 22 11:40:27 2019 -- 256 IP addresses (1 host up) scanned in 45.17 seconds
Traceback (most recent call last):
  File "/output_report.py", line 225, in <module>
    main()
  File "/output_report.py", line 216, in main
    parse_results(data)
  File "/output_report.py", line 102, in parse_results
    parse_host(h)
  File "/output_report.py", line 92, in parse_host
    parse_port(ip_addr, p)
  File "/output_report.py", line 83, in parse_port
    parse_script(ip_addr, port_num, app_name, scripts)
  File "/output_report.py", line 35, in parse_script
    script_table = script['table']['table']
KeyError: 'table'
sed: /shared/reports/report_2019.11.22-10.57.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-10.57.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-10.57.tex: No such file or directory
```

My IPs are three /24 networks.

**Comment by Demonslay335** [comment]
I also ran into this issue with another key not found. Also three /24 networks.

Perhaps some checks for the keys should be done before assigning?

`# Nmap done at Mon Nov 25 22:25:43 2019 -- 0 IP addresses (0 hosts up) scanned in 1.59 seconds
Traceback (most recent call last):
  File "/output_report.py", line 227, in <module>
    main()
  File "/output_report.py", line 218, in main
    parse_results(data)
  File "/output_report.py", line 98, in parse_results
    hosts = data['nmaprun']['host']
KeyError: 'host'
sed: /shared/reports/report_2019.11.25-19.45.tex: No such file or directory
sed: /shared/reports/report_2019.11.25-19.45.tex: No such file or directory
sed: /shared/reports/report_2019.11.25-19.45.tex: No such file or directory
sed: /shared/reports/report_2019.11.25-19.45.tex: No such file or directory`

**Comment by alexpdp7** [comment]
Do you mean `shared/xml_files`? 
[flan_issue_11.zip](https://github.com/cloudflare/flan/files/3891410/flan_issue_11.zip)

**Comment by nadinelyab** [comment]
Hi @alexpdp7, 
Thanks for passing along those files. It looks like the issue was that there was an error at some point in the Vulners script and that is why the report wasn't being generated. I added some code to handle this type of error and print out the error message. It should generate the report now.
