### ISSUE TITLE
Kubernetes CronJob instead of Deployment?

### ISSUE THREAD

**Issue by iamacarpet** [cloudflare/flan#12]
Hello,

If I'm understanding the entrypoint (`run.sh`) correctly, it just runs the once then exists.

I suppose Kubernetes will continually restart it, but with an exponential backoff?

Would it be better to run it as a scheduled batch job using the CronJob object type?

Regards,
iamacarpet

**Comment by Helithumper** [comment]
I second this. What is the deployment plan for K8s if not as a CronJob? Theoretically, Flan _should_ be run on a schedule (once a week, etc...) and then send out the report. A CronJob is the only deployment strategy that makes sense as far as I am understanding.

Was there a design choice as to why it is a Deployment instead?

**Comment by nadinelyab** [comment]
Hey thanks for suggesting this. I actually already had a K8s CronJob file that I had written but hadn't uploaded it to `flan` because I thought the deployment was similar enough. In any case I've now added it under a new folder called `kubernetes_templates`.
