### ISSUE TITLE
Markdown report support

### ISSUE THREAD

**Issue by marciorgb** [cloudflare/flan#13]
For the output the LaTeX file are not that usual, and can not be show in the repo in a human readable format.

I believe the best format for the report's output's is a Makrdown because it can be shown in the Github ,or something else, in a easier way.

Also, form what I saw the output is simple and only have colorful boxes for the severity. These can be handler by the Markdown file

**Comment by jackusm** [comment]
i am interested and working on a solution for this, in the meantime pandoc

**Comment by willichan** [comment]
Just so long as the LaTeX option remains for those of us that prefer it.
