### ISSUE TITLE
start container with local time

### ISSUE THREAD

**Issue by acbekoac** [cloudflare/flan#18]
start_linux : 
	docker run --name $(container_name) -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v $(shell pwd)/shared:/shared flan_scan

**Comment by SuperSandro2000** [comment]
You probably want to add tzdata to the container or it will not work probably in alpine.

**Comment by nadinelyab** [comment]
Hey @acbekoac, I tried your command but since I'm running in OSX `/etc/timezone` doesn't exist. I would rather not introduce environment specific configuration like this since the point is to be able to run flan scan easily.
