### ISSUE TITLE
The generated .tex file is not valid sometimes.

### ISSUE THREAD

**Issue by Tim-NL** [cloudflare/flan#2]
**What?**
When I tried to generate a PDF from the .tex report, it failed to compile. 

**When?**
The issue seems to only occur when no vulnerabilities are found.

The issue seems to be resolved when I add a random \item within the "Services with Vulnerabilities" section, as it seems to require at least one "item".

```
\section*{Services with Vulnerabilities}
\begin{enumerate}[wide, labelwidth=!, labelindent=0pt,  label=\textbf{\large \arabic{enumi} \large}]
\item this has been added
\end{enumerate}
```

Note: I'm not familiar with the TeX format, and I'm not sure if this is even an issue with Flan.

-Tim

**Comment by mbeacom** [comment]
@Tim-NL Would you say reproduction steps would be to generating an empty vulnerabilities section?

**Comment by Tim-NL** [comment]
I was checking two servers that did not have any vulnerabilities. As no servers were vulnerable from the report, the list would be empty, thus causing the issue for me.

-Tim

**Comment by nadinelyab** [comment]
Thanks for reporting this @Tim-NL. I just pushed a fix for this.
