### ISSUE TITLE
Prometheus metrics output

### ISSUE THREAD

**Issue by jfrabaute** [cloudflare/flan#23]
Hi,

Thanks for this great tool.
When running it for a kubernetes cluster, it could be nice to output the result as prometheus metrics, so it could be scraped, allow graphing and generate alerts.

**Comment by nadinelyab** [comment]
Hi @jfrabaute ,
This is a great idea. I worked on something like this for a bit that reported the number of high, medium, and low vulnerabilities. It would definitely be cool to add more metrics beyond these and could be a feature I or anyone else in the community adds to flan in the future.
