### ISSUE TITLE
Code incompatible with Python 3

### ISSUE THREAD

**Issue by nbuzydeb** [cloudflare/flan#34]
In [aws_push.py](https://github.com/cloudflare/flan/blob/master/aws_push.py), the code used to process the exception is only valid on Python 2.

In order to work on Python 3, it should use the "as" keyword instead of the comma syntax. More info [here](https://techglimpse.com/difference-comma-as-python-except-statement/).

![image](https://user-images.githubusercontent.com/10597937/69615951-bbb7fc00-1070-11ea-9a3c-e358284d157c.png)

**Comment by nadinelyab** [comment]
Nice thank you!
