### ISSUE TITLE
Report generation failure

### ISSUE THREAD

**Issue by alexpdp7** [cloudflare/flan#37]
As a follow up to https://github.com/cloudflare/flan/issues/11 , after `git pull` now I get...

```
ERROR in script: ERROR: Script execution failed (use -d to debug) at location: 10.76.78.124 port: 8080 app: http (cpe:/a:jeremy_graham:chorus:2) 
```

**Comment by nadinelyab** [comment]
Yes I added that line to be printed from `output_report.py` in the latest commit but the original error happened when in the Nmap run. Could you try to rerun the entire scan and see if you still see that error in the output?

**Comment by alexpdp7** [comment]
Yeah, sorry, the error is printed, but a `.tex` file is generated, so I think this can be closed.
