### ISSUE TITLE
Vulners script does not appear to execute

### ISSUE THREAD

**Issue by 0sm0s1z** [cloudflare/flan#39]
Example output from across many runs. Any guidance on troubleshooting?
```
root@kali:~/tools/flan# make start
docker run --name flan_1574871383 -v /root/tools/flan/shared:/shared flan_scan
# Nmap 7.70 scan initiated Wed Nov 27 16:16:24 2019 as: nmap -sV -oX /shared/xml_files/2019.11.27-16.16/192.168.86.237.xml -oN - -v1 --script=vulners/vulners.nse 192.168.86.237
Nmap scan report for *****
Host is up (1.8s latency).
Not shown: 993 closed ports
PORT     STATE    SERVICE      VERSION
80/tcp   open     http         nginx 1.13.5
|_http-server-header: nginx/1.13.5
135/tcp  open     msrpc        Microsoft Windows RPC
139/tcp  open     netbios-ssn  Microsoft Windows netbios-ssn
445/tcp  open     microsoft-ds Microsoft Windows 7 - 10 microsoft-ds (workgroup: WORKGROUP)
514/tcp  filtered shell
1556/tcp open     msrpc        Microsoft Windows RPC
5357/tcp open     http         Microsoft HTTPAPI httpd 2.0 (SSDP/UPnP)
|_http-server-header: Microsoft-HTTPAPI/2.0
Service Info: Host: ****; OS: Windows; CPE: cpe:/o:microsoft:windows

Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Wed Nov 27 16:29:05 2019 -- 1 IP address (1 host up) scanned in 760.65 seconds
```

**Comment by nadinelyab** [comment]
@0sm0s1z Is it possible that vulners script is running but there are no vulnerabilities in the services Nmap detected?

**Comment by 0sm0s1z** [comment]
Not likely. This system is vulnerable to eternalblue. I also executed against an unpatched server 2003 system. With everything from IIS to MSSQL and SharePoint installed.

**Comment by nelly113113** [comment]
Can you run nmap with -d flag, add more 'd's for deeper info

**Comment by adi928** [comment]
In the documentation, they mention that:

> the -oN - flag outputs "normal" Nmap results to the console.

Either remove that flag, or check the xml report it generates.

**Comment by 0sm0s1z** [comment]
I've figured out the issue with some debugging and tcpdump. It seems to be related to the vulners api/correlation/script and not an actual issue with flan.

Screenshot attached, and closing this issue.

![image](https://user-images.githubusercontent.com/11495216/70130482-a170b600-164e-11ea-9c47-2589db9655ce.png)
