### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by 0x01h** [cloudflare/flan#43]
Hello,

I'm getting this error on `make start`.

```
docker run --name flan_1575283883 -v /Users/xxx/flan/shared:/shared flan_scan
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
make: *** [start] Error 125
```

**Comment by nadinelyab** [comment]
Hi @0x01h,
Thanks for reporting this. It looks like this could be caused if there is a space in directory path where you have cloned flan. I have added a fix to the Makefile to address this. Please let me know if it did not fix your issue. Thanks!
