### ISSUE TITLE
Produce the report in HTML, not LaTeX.

### ISSUE THREAD

**Issue by max0x7ba** [cloudflare/flan#44]
I spent 30 minutes installing various LaTeX packages and extra fonts on Ubuntu 18.04 to be able to view the LaTeX report the scan generates.

Reports in LaTeX format is a usability bug.

Just generate report in plain HTML.

**Comment by marius-udubasa** [comment]
I was able to have a quick pdf quality result by just pasting the tex file content (you can import the file too) into the online tool from here https://www.overleaf.com/ and then using Recompile and pdf download

**Comment by max0x7ba** [comment]
> I was able to have a quick pdf quality result by just pasting the tex file content (you can import the file too) into the online tool from here https://www.overleaf.com/ and then using Recompile and pdf download

Your report may well contain sensitive information about public IP addresses, you don't want to share it with any 3rd-parties.

**Comment by marius-udubasa** [comment]
True. That may be a good idea. Not to mention this is a manual step.
As far as the privacy for that service goes, they do state that any uploaded files are private and only belong to the uploader:
https://www.overleaf.com/legal

**Comment by max0x7ba** [comment]
> As far as the privacy for that service goes, they do state that any uploaded files are private and only belong to the uploader:
> https://www.overleaf.com/legal

That change that overnight, or they can be hacked.
