### ISSUE TITLE
Set default ips.txt to 192.168.1.0/24.

### ISSUE THREAD

**Issue by max0x7ba** [cloudflare/flan#45]
The random IPs in `ips.txt` are less than ideal. `192.168.1.0/24` is a better default.

**Comment by nadinelyab** [comment]
Thanks for the suggestion. I'd like to leave these two default IPs because they lead to a pretty quick first scan for those just quickly trying out Flan. An entire `/24` could a long time and users would not be able to quickly see the reports created after the scan.
