### ISSUE TITLE
report sources don't escape underscore

### ISSUE THREAD

**Issue by akhepcat** [cloudflare/flan#6]
When the TEX file is generated, it doesn't properly escape underscore characters.
This results in the character following the underscore to become a subscript.  Additionally, texitopdf (for instance)  complains madly about the resulting TEX file trying to figure out what is meant by missing math symbols.

A simple input filter when reading the nmap reports and vulnerability reports to transform '\_'  into '\\_'  will suffice.

**Comment by ghane** [comment]
This should be working, see the last few lines of run.sh

**Comment by akhepcat** [comment]
yeah, i see that it should be...  
I'm not so experienced with docker, so trying to debug the script running has been challenging.
But there's definitely something failing before those scripts run, and i'm not sure what.

time to wipe and re-pull the repo, i guess

**Comment by nadinelyab** [comment]
@akhepcat could you post the output when you run flan? If you're seeing something failing before those scripts it would be helpful to see those error messages.

**Comment by akhepcat** [comment]
wiped all docker images, re-pulled the git repo.
now working as expected. Very odd.
